### ISSUE TITLE
Progressive Rail disables Maglev level crossings

### ISSUE THREAD

**Issue by GrantSWatson** [minchinweb/openttd-progressive-rail#1]
Went for a bit of a search and did some testing to see what was causing this. When I add the Progressive Rails to the game, I can no longer make Maglev level crossings, nor can I upgrade monorail or rail tracks which are level crossings. This causes some confusion when I tried to mass convert my track as you can imagine! 

Is this behaviour intentional?

**Comment by minchinweb** [comment]
Hi @GrantSWatson! Turning off Maglev level crossing was a design decision on my part; it seemed that at some point the train speeds get to fast to (safely) allow level crossings.

My though process when moving from monorails to maglev was to bulk upgrade most of the network to maglev, upgrade the trains that only run on all-maglev track, then work trough and upgrade away any level crossings, and then upgrade the rest of your trains.

Vac trains don't allow level crossings either.

Hope this helps!
