### ISSUE TITLE
Not working in game where NewGRF applied after creation of game.

### ISSUE THREAD

**Issue by osmarks** [minchinweb/openttd-progressive-rail#2]
![flontburg transport 18th aug 1998](https://cloud.githubusercontent.com/assets/10486993/21079976/e14084a8-bf9a-11e6-868e-d91d1382c624.png)
I created a game (in 1950 with no monorails) then activated this mod later. Now monorails have been invented and my electric trains can't go over them (see attached screenshot). Is this just because it doesn't work if applied after game creation?

**Comment by minchinweb** [comment]
Loading or activating NewGRF's after the game start can cause many issues... In fact, it's the cause of enough random bugs that the OpenTTD devs removed the ability to change NewGRF's after the game has started (unless you turn on developer tools), and refuse to follow up on bugs that result from changing NewGRF's in-game.

So I'm not sure what exactly broke, or how to fix it (beyond starting a new game). I'm sorry that doesn't help your current game much :(
